#
# writeabsorption.py
#
# Writes the Absorptionspectrum as generated by Absorption() into a file.
#
def WriteAbsorption(w,Abs,filename="Demo",overwrite=False):
    import numpy as np

    # Create "data" folder if it does not exists already
    InitDataFolder()

    # Find filename
    filename = DetermineFileName(filename,overwrite)

    # Create path
    path = './data/' + filename + '.txt'

    # Combine w and Abs into one data array
    Data = np.concatenate((w, Abs), axis=1)

    # Format to 10 digits scientific notation
    fmt = ",".join(["%10.10e"] * (Data.shape[1]-1))

    # Write to file.
    with open(path, 'wb') as f:
        # Write header
        f.write(b'Frequency,Absorption\n')
        # Save comma delimited file
        np.savetxt(f, Data, fmt=fmt, delimiter=",")

#
# Finds the filename to write to based on some auxilerairy arguments.
# Returns filename
#
def DetermineFileName(filename,overwrite):
    # If no filename is given (then filename = "Demo") then generate new filename.
    if (filename == "Demo"):
        import datetime
        import getpass
        user = getpass.getuser()
        currentDT = datetime.datetime.now()
        filename = currentDT.strftime("%Y%m%d_%H%M") + "_" + user + "_LinAbsSpec"

    # If no overwrite is permitted, find next filename to write to
    if (False == overwrite):
        import os
        # Create path
        path = './data/' + filename + '.txt'

        # Start counting at 2, because the first might be already written
        count = 2

        # Check if file already exists, if so, then add number to end of file and try again.
        while (os.path.exists(path)):
            filename = filename + str(count)
            count = count + 1

    return filename
    
#
# Sets up data folder
#
def InitDataFolder():
    import os

    # Check if Data folder exists, If not create it
    if (False == os.path.isdir('./data')):
        print('No data dir available, creating one now ...')
        os.makedirs('./data')
